### ISSUE TITLE
Unable to build it on Arch-based Linux distro

### ISSUE THREAD

**Issue by Joe23232** [clearlinux/clr-power-tweaks#19]
So after typing this on terminal `yay -S clr-power-tweaks` it fails to build.

```
==> ERROR: A failure occurred in build().
    Aborting...
Error making: clr-power-tweaks
```

Any idea how to solve this?

**Comment by bryteise** [comment]
Clone configure and make and see if it gives more information. Or talk to the aur maintainer.

**Comment by ahkok** [comment]
@seanvk lol, as he added it to AUR.

**Comment by Joe23232** [comment]
I am kinda new to Linux so sorry for the lack of knowledge but when I git cloned the repo, I cd inside the directory and then when I ran `makepkg -si` I got an error message which outputted:

```
==> ERROR: PKGBUILD does not exist.
```

Any idea how to build this and install it?

**Comment by bryteise** [comment]
So the tools you have learned to build software in Arch are Arch specific (makepgk uses a PKGBUILD configuration file as a recipe for creating an Arch package file that can be installed and uninstalled using pacman). Most software doesn't have distro specific packaging recipes and instead uses a more generic set of build system tools. In the case of clr-power-tweaks we use autotools, and specifically [autoconf](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/autoconf.html) and [automake](https://www.gnu.org/software/automake/manual/automake.html) (which generates [Makefiles](https://www.gnu.org/software/make/manual/html_node/index.html)) as its build system. Learning to use these tools is a bit outside the scope of this issue but `autoreconf -fi && ./configure && make` should attempt to build clr-power-tweaks and give us an idea if you are missing some tooling to enable it to be built. From there you'll want to learn how arch PKGBUILD scripts work in order to fix the packaging of clr-power-tweaks in AUR for yourself or ask @seanvk to use your fix.

**Comment by bryteise** [comment]
@ahkok I think this points to an issue for the README that it often has simple build instructions for the project in it for folks who aren't very experienced in building and installing software themselves. Do you feel like we should add that?

**Comment by seanvk** [comment]
@Joe23232 You should leave a comment on AUR for the package next time and I'll look at it.  Package updated with changes resulted from Glibc-2.31 making stime() obsolete.  Bumped to release 207.

**Comment by ahkok** [comment]
c8928a1144779ba8c5b172d0935ba4d3bafe0ac0 solves the "how do I build" documentation issue. I will also upload release tarballs in the future, after I merge the next major PR.

**Comment by Joe23232** [comment]
@seanvk Sure next time I will do that. Its now working fine.

**Comment by Joe23232** [comment]
@bryteise @ahkok Thanks for your guys help, how would I now enable it after installation?

**Comment by ahkok** [comment]
`man systemctl` covers that.
